GO
USE MASTER
GO
DROP DATABASE NINERFISTAGING
GO
CREATE DATABASE NINERFISTAGING
GO
USE NINERFISTAGING
GO
CREATE TABLE [STAGING] (
	UID uniqueidentifier NOT NULL DEFAULT (NEWID()),
	EntryTimestamp datetime NOT NULL,
	Hostname nchar(50),
	IPAddress nchar(13) NOT NULL,
	ProcessName nchar(10) NOT NULL,
	ProcessNumber int NOT NULL,
	LogCode int NOT NULL,
	Description ntext,
	EntryTypeName nchar(5) NOT NULL,
  CONSTRAINT [PK_STAGING] PRIMARY KEY CLUSTERED
  (
  [UID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO



USE [NINERFISTAGING]
GO
CREATE USER [CAPSTONE\aidenl] FOR LOGIN [CAPSTONE\aidenl]
GO
USE [NINERFISTAGING]
GO
ALTER ROLE [db_owner] ADD MEMBER [CAPSTONE\aidenl]
GO
CREATE USER [CAPSTONE\willr] FOR LOGIN [CAPSTONE\willr]
GO
USE [NINERFISTAGING]
GO
ALTER ROLE [db_owner] ADD MEMBER [CAPSTONE\willr]
GO
